word_list = [
    'apple-pie',
    'strawberry-pie',
    'juice-box',
    'code-institution',
    'cheese-slicer',
    'cheese-grater',
    'dark chocolate',
    'cheese cake',
    'different timezone',
    'tea pot',
    'living room',
    'full moon',
    'real estate',
    'ice cream',
    'hot dog',
    'corn dog',
    'corned beef',
    'ice cube',
    'cream cheese',
    'corned beef',
    'sugar plum',
    'web page',
    'table cloth',
    'fire drill',
    'fire exit',
    'high school',
    'roller coaster',
    'first aid',
    'tea cup',
    'serving spoon',
    'car pool',
    'cotton bud',
    'cotton ball',
    'video game',
    'coffee grain',
    'coffee mug',
    'post office',
    'upper deck',
    'hand towel',
    'sweet tooth',
    'common sense',
    'dance hall',
    'police officer',
    'vice president',
    'science fiction',
    'root word',
    'candy cane',
    'christmas tree',
    'cell membrane',
    'jumping jack',
    'report card',
    'credit card',
    'debit card',
    'radio wave',
    'snack house',
    'coffee shop',
    'bus stop',
    'swimming pool',
    'rubber band',
    'ice hockey',
    'ice skate',
    'break up',
    'take away',
    'take out',
    'break away',
    'lift up',
    'push down',
    'pull down',
    'ask out',
    'ask around',
    'make up',
    'make out',
    'turn in',
    'fill up',
    'fill out',
    'fill in',
    'high school',
    'school bus',
    'science fiction',
    'blood pressure'
]
